services:
  postgres:
    image: postgres:16-alpine
    container_name: estoque-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_control_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
